package memory

import (
	"regexp"
	"strings"
	"unicode"
)

// Not every "user" message was typed by the user. Each tool injects context
// into the conversation wearing the user role: the whole of AGENTS.md or
// CLAUDE.md at session start, environment blocks, the echoed output of slash
// commands, hook output. Taken as a title, these produce notes all called
// "# AGENTS.md instructions", which is how you end up with a memory that
// remembers nothing.
var injectedPrefixes = []string{
	"# AGENTS.md instructions",
	"<INSTRUCTIONS>",
	"<environment_context>",
	"<user_instructions>",
	"<system-reminder>",
	"<command-name>",
	"<local-command-stdout>",
	"<turn_aborted>",
	"Caveat: The messages below were generated by the user while running",
}

// fencedTags are the wrappers the tools put around injected material. Each
// gets its own pattern because Go's regexp is RE2 and has no backreferences,
// so a single `<(\w+)>.*?</\1>` is not available — and the alternative,
// stripping every `<...>` and keeping what is between, would leave the echoed
// body of a slash command looking like something a person typed.
var fencedTags = []string{
	"system-reminder", "INSTRUCTIONS", "environment_context", "user_instructions",
	"command-name", "command-message", "command-args", "turn_aborted",
	"local-command-stdout", "local-command-stderr",
	"thinking", "function_results",
}

var tagBlocks = func() []*regexp.Regexp {
	out := make([]*regexp.Regexp, 0, len(fencedTags))
	for _, t := range fencedTags {
		out = append(out, regexp.MustCompile(`(?is)<`+regexp.QuoteMeta(t)+`\b[^>]*>.*?</`+regexp.QuoteMeta(t)+`\s*>`))
	}
	return out
}()

// stripFenced removes every known injected block from s.
func stripFenced(s string) string {
	for _, re := range tagBlocks {
		s = re.ReplaceAllString(s, " ")
	}
	return s
}

// IsInjected reports whether a message body is tool machinery rather than
// something a person typed.
func IsInjected(text string) bool {
	t := strings.TrimSpace(text)
	if t == "" {
		return true
	}

	// Strip complete fenced blocks first, then judge what is left. Testing the
	// prefixes first would discard a real question that merely happens to have
	// a reminder stapled to the front of it — which is the common shape, not an
	// edge case, since the tools prepend their machinery to what you typed.
	stripped := strings.TrimSpace(stripFenced(t))
	if stripped == "" {
		return true
	}
	// The prefix list still applies to the remainder: it catches the markers
	// that have no closing tag, and tags left unclosed by a truncated line.
	for _, p := range injectedPrefixes {
		if strings.HasPrefix(stripped, p) {
			return true
		}
	}
	return strings.IndexFunc(stripped, unicode.IsLetter) < 0
}

// filler is what a person types to keep a session moving rather than to say
// something. These make useless titles — a digest reading "· continue" tells
// you nothing about what the session was, which is the one job it has.
var filler = map[string]bool{
	"continue": true, "continue.": true, "keep going": true, "go on": true,
	"go ahead": true, "proceed": true, "resume": true, "next": true,
	"ok": true, "okay": true, "yes": true, "no": true, "yep": true, "sure": true,
	"do it": true, "please continue": true, "carry on": true, "thanks": true,
	"y": true, "n": true, "k": true, "fix it": true, "again": true, "retry": true,
}

// isFiller reports whether a message is too slight to name a session by.
func isFiller(s string) bool {
	t := strings.ToLower(strings.TrimSpace(s))
	t = strings.Trim(t, ".!? ")
	if filler[t] {
		return true
	}
	// Very short messages are nearly always acknowledgements. The threshold is
	// deliberately low: a real instruction that short ("ship it") is rare, and
	// losing one to the fallback below costs nothing.
	return len(t) < 12
}

// FirstPrompt returns the message that best names the session.
//
// It prefers the first substantive thing the user typed over the literal first
// one, because sessions are routinely resumed with "continue" and a digest full
// of that entry is a digest that has forgotten everything. The literal first
// message is the fallback, so a session of nothing but short messages still
// gets a title rather than none.
func FirstPrompt(texts []string) string {
	var fallback string
	for _, t := range texts {
		if IsInjected(t) {
			continue
		}
		if isFiller(t) {
			if fallback == "" {
				fallback = t
			}
			continue
		}
		return TitleLine(t)
	}
	return TitleLine(fallback)
}

// TitleLine reduces a message to one short line. Titles land in filenames and
// in a digest with a hard byte budget, so length is capped here rather than at
// each call site.
func TitleLine(s string) string {
	s = strings.TrimSpace(stripFenced(s))
	// Markdown headings and list markers read badly as a title.
	s = strings.TrimLeft(s, "#-*> \t")
	if i := strings.IndexAny(s, "\r\n"); i >= 0 {
		s = s[:i]
	}
	s = strings.Join(strings.Fields(s), " ")

	const maxTitle = 80
	if len(s) > maxTitle {
		// Cut on a rune boundary, then back off to the last space so the
		// title does not end mid-word.
		cut := maxTitle
		for cut > 0 && !isBoundary(s, cut) {
			cut--
		}
		trimmed := strings.TrimSpace(s[:cut])
		if sp := strings.LastIndex(trimmed, " "); sp > maxTitle/2 {
			trimmed = trimmed[:sp]
		}
		s = trimmed + "…"
	}
	return s
}

func isBoundary(s string, i int) bool {
	if i <= 0 || i >= len(s) {
		return true
	}
	return s[i]&0xC0 != 0x80 // not a UTF-8 continuation byte
}

// SafeFilename turns a title into something writable on macOS and Linux and
// harmless in an iCloud-synced directory.
func SafeFilename(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r == '/' || r == '\\' || r == ':' || r == '\x00':
			b.WriteRune(' ')
		case unicode.IsControl(r):
			// drop
		default:
			b.WriteRune(r)
		}
	}
	out := strings.Join(strings.Fields(b.String()), " ")
	// Separators are already gone, so ".." cannot traverse — but a title
	// beginning with dots produces a hidden file, and a vault full of
	// ".. .. etc passwd.md" is unreadable. Collapse runs of dots and never
	// begin with one.
	for strings.Contains(out, "..") {
		out = strings.ReplaceAll(out, "..", ".")
	}
	out = strings.TrimLeft(out, ". ")

	const maxBase = 60
	if len(out) > maxBase {
		cut := maxBase
		for cut > 0 && !isBoundary(out, cut) {
			cut--
		}
		out = strings.TrimSpace(out[:cut])
	}
	return strings.TrimRight(out, ". ")
}
