package memory

import (
	"strings"
	"testing"
	"unicode/utf8"
)

// Injected context arrives wearing the user role in every tool. Counting or
// titling from it produces notes called "AGENTS.md instructions" — a memory
// that remembers the instructions and nothing else.
func TestIsInjected(t *testing.T) {
	injected := []string{
		"# AGENTS.md instructions\n\nfollow these",
		"<system-reminder>do not mention this</system-reminder>",
		"<command-name>/clear</command-name>",
		"<turn_aborted>\nThe user interrupted the previous turn.\n</turn_aborted>",
		"Caveat: The messages below were generated by the user while running a command",
		"",
		"   \n\t ",
		"<local-command-stdout></local-command-stdout>",
	}
	for _, s := range injected {
		if !IsInjected(s) {
			t.Errorf("IsInjected(%.40q) = false, want true", s)
		}
	}

	human := []string{
		"fix the failing test in store.go",
		"why does this panic?",
		"<system-reminder>ignore</system-reminder> now actually explain the cache",
	}
	for _, s := range human {
		if IsInjected(s) {
			t.Errorf("IsInjected(%.40q) = true, want false", s)
		}
	}
}

// A digest line reading "· continue" tells you nothing, and sessions resumed
// that way are common.
func TestFirstPromptPrefersSubstance(t *testing.T) {
	got := FirstPrompt([]string{
		"<system-reminder>x</system-reminder>",
		"continue",
		"ok",
		"rewrite the fleet cache to use an explicit schema version",
	})
	want := "rewrite the fleet cache to use an explicit schema version"
	if got != want {
		t.Errorf("FirstPrompt = %q, want %q", got, want)
	}
}

// But a session that really was only "continue" still gets a title rather than
// none — an empty title loses the session from the index entirely.
func TestFirstPromptFallsBackToFiller(t *testing.T) {
	if got := FirstPrompt([]string{"continue"}); got != "continue" {
		t.Errorf("FirstPrompt = %q, want %q", got, "continue")
	}
	if got := FirstPrompt([]string{"<system-reminder>x</system-reminder>"}); got != "" {
		t.Errorf("FirstPrompt = %q, want empty", got)
	}
}

func TestTitleLineIsOneShortValidLine(t *testing.T) {
	long := strings.Repeat("télémétrie ", 40) // multi-byte, well over the cap
	got := TitleLine("# " + long + "\nsecond line")

	if strings.ContainsAny(got, "\r\n") {
		t.Errorf("title spans lines: %q", got)
	}
	if !utf8.ValidString(got) {
		t.Errorf("title cut mid-rune: %q", got)
	}
	if len(got) > 90 {
		t.Errorf("title too long (%d bytes): %q", len(got), got)
	}
	if strings.HasPrefix(got, "#") {
		t.Errorf("markdown heading marker survived: %q", got)
	}
}

// Titles become filenames in an iCloud-synced vault, so path separators and
// control characters cannot survive.
func TestSafeFilename(t *testing.T) {
	got := SafeFilename("fix internal/dots: the C:\\path\x00 bug\n")
	for _, bad := range []string{"/", "\\", ":", "\x00", "\n"} {
		if strings.Contains(got, bad) {
			t.Errorf("SafeFilename kept %q: %q", bad, got)
		}
	}
	if got == "" {
		t.Error("SafeFilename returned empty for a usable title")
	}

	if got := SafeFilename(strings.Repeat("あ", 100)); !utf8.ValidString(got) {
		t.Errorf("SafeFilename cut mid-rune: %q", got)
	}
}
